// Heartopia Wiki Data

export const PECES = {
  "Coregono": { "ubicacion": "Mar de Céfiro", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Barbo Común": { "ubicacion": "Río Poco Profundo", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Alburno": { "ubicacion": "Lago", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Perca Europea": { "ubicacion": "Río", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cacho": { "ubicacion": "Lago", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Locha de Espina": { "ubicacion": "Río del Bosque Gigante", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pequeño Pez de Río": { "ubicacion": "Río Tranquilo", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tenca": { "ubicacion": "Lago del Bosque", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Carpa Gibelio": { "ubicacion": "Lago", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Schneider": { "ubicacion": "Lago Suburbano", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Sardina": { "ubicacion": "Océano", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lubina": { "ubicacion": "Océano", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Camarón Oriental": { "ubicacion": "Río", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Listado": { "ubicacion": "Océano", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Sable": { "ubicacion": "Mar de Céfiro", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Camarón Común": { "ubicacion": "Mar del Este", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Jurel": { "ubicacion": "Mar de la Ballena", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Espinoso Marino": { "ubicacion": "Mar Viejo", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Salmonete de Roca": { "ubicacion": "Pesca Marina", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Eperlán Europeo": { "ubicacion": "Lago de la Pradera", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Caballito de Mar": { "ubicacion": "Mar de la Ballena", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día"] },
  "Pulpo Común": { "ubicacion": "Pesca Marina", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Locha de Piedra": { "ubicacion": "Lago Suburbano", "nivel": 2, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Jurel Falso": { "ubicacion": "Mar de Céfiro", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Abisal": { "ubicacion": "Pesca Marina", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pulpo Pigmeo del Atlántico": { "ubicacion": "Mar de la Ballena", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Rodaballo": { "ubicacion": "Pesca Marina", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lubina Negra": { "ubicacion": "Lago del Bosque", "nivel": 2, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Salmón del Atlántico": { "ubicacion": "Mar de la Ballena", "nivel": 3, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Pez Payaso": { "ubicacion": "Mar Viejo", "nivel": 3, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lucioperca": { "ubicacion": "Río del Bosque Gigante", "nivel": 3, "tipo": "Río", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Acerina": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 3, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Rana Comestible": { "ubicacion": "Lagos", "nivel": 3, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cangrejo Ermitaño": { "ubicacion": "Mar del Este", "nivel": 3, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Sol del Fango": { "ubicacion": "Lago del Bosque", "nivel": 3, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Tilapia": { "ubicacion": "Ríos", "nivel": 3, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Streber": { "ubicacion": "Río Rosado", "nivel": 3, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cangrejo de Río Europeo": { "ubicacion": "Lago del Bosque", "nivel": 3, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche", "Amanecer"] },
  "Carpa Común": { "ubicacion": "Río Rosado", "nivel": 4, "tipo": "Río", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Lota": { "ubicacion": "Río Tranquilo", "nivel": 4, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Día"] },
  "Solla": { "ubicacion": "Mar Viejo", "nivel": 4, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche", "Amanecer"] },
  "Gobio": { "ubicacion": "Mar del Este", "nivel": 4, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer", "Amanecer"] },
  "Mejillón": { "ubicacion": "Lago Suburbano", "nivel": 4, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Conejo": { "ubicacion": "Océano", "nivel": 4, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cangrejo de Río": { "ubicacion": "Lago Suburbano", "nivel": 4, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Renacuajo": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 4, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Trucha": { "ubicacion": "Lago de la Pradera", "nivel": 5, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche", "Amanecer"] },
  "Koi Mariposa": { "ubicacion": "Lago de la Pradera", "nivel": 5, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Caballa del Atlántico": { "ubicacion": "Mar de la Ballena", "nivel": 5, "tipo": "Mar", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Rutilo": { "ubicacion": "Lago Suburbano", "nivel": 5, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Calamar Volador Europeo": { "ubicacion": "Pesca Marina", "nivel": 5, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Langosta Europea": { "ubicacion": "Mar de Céfiro", "nivel": 5, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Blenio de Agua Dulce": { "ubicacion": "Río Rosado", "nivel": 5, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Piraña de Vientre Rojo": { "ubicacion": "Río del Bosque Gigante", "nivel": 5, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Salmón Keta": { "ubicacion": "Río Tranquilo", "nivel": 6, "tipo": "Río", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tímalo": { "ubicacion": "Lago Suburbano", "nivel": 6, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mejillón de Perla Grande": { "ubicacion": "Lago del Bosque", "nivel": 6, "tipo": "Lago", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lija": { "ubicacion": "Pesca Marina", "nivel": 6, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Globo": { "ubicacion": "Mar Viejo", "nivel": 6, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Rubio": { "ubicacion": "Mar del Este", "nivel": 6, "tipo": "Mar", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Besugo": { "ubicacion": "Mar de Céfiro", "nivel": 7, "tipo": "Mar", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Atardecer"] },
  "Anguila Europea": { "ubicacion": "Mar Viejo", "nivel": 7, "tipo": "Mar", "clima": ["Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Fartet del Mediterráneo": { "ubicacion": "Lago Suburbano", "nivel": 7, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Pez Remo Gigante": { "ubicacion": "Pesca Marina", "nivel": 7, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Esculpin Moteado": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 7, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Espinoso": { "ubicacion": "Río Poco Profundo", "nivel": 7, "tipo": "Río", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cangrejo de Río Azul": { "ubicacion": "Lago del Bosque", "nivel": 8, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Umbra Europea": { "ubicacion": "Lago Suburbano", "nivel": 8, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer"] },
  "Cangrejo Real Dorado": { "ubicacion": "Pesca Marina", "nivel": 8, "tipo": "Mar", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Dorado": { "ubicacion": "Lago de la Pradera", "nivel": 8, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Atún de Aleta Azul": { "ubicacion": "Pesca Marina", "nivel": 9, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Huchón": { "ubicacion": "Río del Bosque Gigante", "nivel": 9, "tipo": "Río", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Luna": { "ubicacion": "Pesca Marina", "nivel": 9, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer"] },
  "Lucio del Norte": { "ubicacion": "Lago Suburbano", "nivel": 9, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Luna Gigante": { "ubicacion": "Mar del Este", "nivel": 9, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Sol": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 9, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Trucha Ártica": { "ubicacion": "Lago del Bosque", "nivel": 10, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Agalla Azul": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 10, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Tiburón Mako": { "ubicacion": "Pesca Marina", "nivel": 10, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Espada": { "ubicacion": "Pesca Marina", "nivel": 10, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Siluro": { "ubicacion": "Lago de la Pradera", "nivel": 10, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Pargo": { "ubicacion": "Mar de Céfiro", "nivel": 10, "tipo": "Mar", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Cangrejo Real": { "ubicacion": "Mar de la Ballena", "nivel": 10, "tipo": "Mar", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] }
};

export const INSECTOS = {
  "Escarabajo Longicornio Alpino": { "ubicacion": "Isla del Bosque", "nivel": 5, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo de la Flor Amatista": { "ubicacion": "Hogar (Rocas)", "nivel": 2, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Hormiga": { "ubicacion": "Aldea de Pescadores (Plaza)", "nivel": 3, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Apolo": { "ubicacion": "Evento Cebo para Insectos", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mariquita Asiática": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 5, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Escarabajo del Espárrago": { "ubicacion": "Campo de Flores", "nivel": 1, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Polilla del Cesto": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 10, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Demoiselle Hermosa": { "ubicacion": "Orilla del Lago del Bosque", "nivel": 6, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Leopardo Hermoso": { "ubicacion": "Aldea de Pescadores (Muelle)", "nivel": 4, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Atardecer"] },
  "Morpho Azul": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 7, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Chinche de Escudo Azul": { "ubicacion": "Aldea de Pescadores (Faro)", "nivel": 6, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Abejorro": { "ubicacion": "Campo de Flores", "nivel": 2, "tipo": "Abeja", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Blanquita de la Col": { "ubicacion": "Aldea de Pescadores", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Carpintera Cerúlea": { "ubicacion": "Aldea de Pescadores (Plaza)", "nivel": 9, "tipo": "Abeja", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Tigre de Castaño": { "ubicacion": "Evento Cebo para Insectos", "nivel": 7, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cigarra": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 4, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Día", "Atardecer"] },
  "Polilla Cometa": { "ubicacion": "Suburbios", "nivel": 8, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Mariposa Azul Común": { "ubicacion": "Área Central", "nivel": 2, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Limonera Común": { "ubicacion": "Suburbios", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Libélula de Cola Blanca": { "ubicacion": "Ribera del Río", "nivel": 4, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mantis de Cabeza de Cono": { "ubicacion": "Montaña Onsen (Ruinas)", "nivel": 9, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Planeador de Pantano Carmesí": { "ubicacion": "Montaña Onsen", "nivel": 7, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Noche", "Día", "Atardecer"] },
  "Escarabajo de la Flor Elegante": { "ubicacion": "Campo de Flores (Montaña Ballena)", "nivel": 7, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Chinche de la Mezquita": { "ubicacion": "Hogar (Rocas)", "nivel": 1, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo de Color Fuego": { "ubicacion": "Montaña Onsen (Onsen)", "nivel": 3, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mariquita de Cuatro Manchas": { "ubicacion": "Montaña Onsen (Lago del Cráter)", "nivel": 4, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Libélula de Cuatro Manchas": { "ubicacion": "Lakeshore Suburbano", "nivel": 2, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mantis Gigante Asiática": { "ubicacion": "Montaña Onsen (Ruinas)", "nivel": 5, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Saltamontes de Oro": { "ubicacion": "Montaña Onsen", "nivel": 1, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo Joya Dorado": { "ubicacion": "Bosque (Puzzle de Salto)", "nivel": 7, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Escarabajo Ciervo Dorado": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 9, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Ala de Pájaro Verde": { "ubicacion": "Suburbios", "nivel": 6, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Escarabajo Tigre Verde": { "ubicacion": "Montaña Onsen", "nivel": 2, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo Hércules": { "ubicacion": "Montaña Onsen (Lago del Cráter)", "nivel": 10, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Escarabajo Cornudo": { "ubicacion": "Aldea de Pescadores (Muelle Este)", "nivel": 8, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Katídido": { "ubicacion": "Campo de Flores (Playa Amatista)", "nivel": 3, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Saltamontes de Bandas Grandes": { "ubicacion": "Suburbios", "nivel": 4, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Libélula Roja Grande": { "ubicacion": "Orilla del Agua", "nivel": 1, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mantis Mediterránea": { "ubicacion": "Montaña Onsen (Acantilado de Piedra)", "nivel": 4, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Mini Polilla Luna": { "ubicacion": "Suburbios", "nivel": 3, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Escarabajo Minotauro": { "ubicacion": "Montaña Onsen (Ruinas)", "nivel": 7, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día"] },
  "Morpho Helena": { "ubicacion": "Campo de Flores (Playa Amatista)", "nivel": 10, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Madreperla": { "ubicacion": "Campo de Flores (Campo del Molino)", "nivel": 9, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer"] },
  "Manto de Luto": { "ubicacion": "Montaña Onsen (Onsen)", "nivel": 5, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día"] },
  "Macaón del Viejo Mundo": { "ubicacion": "Bosque", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Punta Naranja": { "ubicacion": "Área Central", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mariposa Pavo Real": { "ubicacion": "Campo de Flores (Campo del Molino)", "nivel": 5, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Chinche Picasso": { "ubicacion": "Campo de Flores (Playa Amatista)", "nivel": 8, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Katídido Rosa": { "ubicacion": "Evento Cebo para Insectos", "nivel": 3, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mariposa Cartero": { "ubicacion": "Evento Cebo para Insectos", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Emperador Púrpura": { "ubicacion": "Campo de Flores (Montaña Ballena)", "nivel": 3, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Día", "Atardecer"] },
  "Escarabajo Ciervo Arcoíris": { "ubicacion": "Evento Cebo para Insectos (Ruinas)", "nivel": 9, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Ala de Pájaro de Rajah Brooke": { "ubicacion": "Hogar", "nivel": 3, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Atardecer"] },
  "Mariquita de Siete Puntos": { "ubicacion": "Suburbios", "nivel": 2, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Saltamontes Siberiano": { "ubicacion": "Aldea de Pescadores", "nivel": 2, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo Joya de Plata": { "ubicacion": "Acantilado Onsen (Lado de árboles)", "nivel": 6, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día"] },
  "Polilla Luna Española": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 8, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Carpintera de Patas Desparramadas": { "ubicacion": "Campo de Flores (Montaña Ballena)", "nivel": 5, "tipo": "Abeja", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo Ciervo": { "ubicacion": "Bosque (Puzzle de Salto)", "nivel": 6, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Morpho de Sulkowsky": { "ubicacion": "Atractor de Insectos Inflable Especial", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Morpho del Atardecer": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 10, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Abeja Cuco de Waroona": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 3, "tipo": "Abeja", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Escarabajo Avispa": { "ubicacion": "Bosque", "nivel": 2, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Bruja Blanca": { "ubicacion": "Evento Cebo para Insectos", "nivel": 5, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] }
};

export const AVES = {
  "Paloma de Oliva Africana": { "ubicacion": "Montaña Onsen (Onsen)", "nivel": 5, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Flamenco Americano": { "ubicacion": "Campo de Flores", "nivel": 9, "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Día"] },
  "Gaviota de Audouin": { "ubicacion": "Mar Ballena (Costas y playas), Playa Amatista", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Herrerillo Azur": { "ubicacion": "Campo de Flores (Campo del Molino)", "nivel": 7, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Bigotudo": { "ubicacion": "Montaña Onsen", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pavo Real Azul": { "ubicacion": "Evento Nido de Cientos", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Guacamayo Azul y Amarillo": { "ubicacion": "Evento Nido de Cientos", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tiñosa Parda": { "ubicacion": "Costa del Mar Antiguo", "nivel": 5, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paloma Terrestre Canela": { "ubicacion": "Aldea de Pescadores (Muelle Este)", "nivel": 6, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cernícalo Vulgar": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 7, "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pinzón de Doble Barra": { "ubicacion": "Aldea de Pescadores (Faro)", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Azulejo de las Montañas": { "ubicacion": "Suburbios", "nivel": 8, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Camachuelo Común": { "ubicacion": "Suburbios", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pinzón Vulgar": { "ubicacion": "Campo de Flores", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tórtola Turca": { "ubicacion": "Hogar", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Oropéndola Europea": { "ubicacion": "Río Rosado, Hogar", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Trepador Azul": { "ubicacion": "Aldea de Pescadores", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Silbón Europeo": { "ubicacion": "Río", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Chochín Común": { "ubicacion": "Bosque", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Abejaruco Europeo": { "ubicacion": "Montaña Onsen (Orilla del Lago)", "nivel": 5, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Petirrojo Europeo": { "ubicacion": "Área Central", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cormorán Moñudo": { "ubicacion": "Océano", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Guacamayo Verde Mayor": { "ubicacion": "Evento Nido de Cientos", "nivel": 5, "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Carbonero Común": { "ubicacion": "Montaña Onsen", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Flamenco Mayor": { "ubicacion": "Orilla del Agua", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Picogordo": { "ubicacion": "Montaña Onsen (Lago del Cráter)", "nivel": 6, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer"] },
  "Cormorán Imperial": { "ubicacion": "Mar del Este / Mar Céfiro", "nivel": 9, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tilopo de Jambu": { "ubicacion": "Suburbios", "nivel": 7, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Eider Real": { "ubicacion": "Río", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Faisán de Lady Amherst": { "ubicacion": "Montaña Onsen (Ruinas)", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Guacamayo de Lear": { "ubicacion": "Evento Nido de Cientos", "nivel": 7, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Flamenco Menor": { "ubicacion": "Orilla del Lago del Bosque", "nivel": 5, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Búho Chico": { "ubicacion": "Montaña Onsen (Acantilado de Piedra)", "nivel": 6, "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mito de Buscapies": { "ubicacion": "Sobre la cabeza de Blanc", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Ánade Real": { "ubicacion": "Lago", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tangara Siete Colores": { "ubicacion": "Suburbios", "nivel": 9, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Halcón Peregrino": { "ubicacion": "Montaña Onsen (Onsen)", "nivel": 7, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Dúcula Imperial": { "ubicacion": "Aldea de Pescadores", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Camachuelo de los Pinos": { "ubicacion": "Isla del Bosque", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paloma Rosa": { "ubicacion": "Campo de Flores (Montaña Ballena)", "nivel": 7, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Vinago Cuellirrojo": { "ubicacion": "Campo de Flores", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paradoxorn de Przevalski": { "ubicacion": "Aldea de Pescadores (Plaza)", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cormorán Carirrojo": { "ubicacion": "Mar Antiguo / Mar Ballena", "nivel": 6, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Guacamayo Rojo y Verde": { "ubicacion": "Evento Nido de Cientos", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Ave de Regente": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tarro Canelo": { "ubicacion": "Lago Suburbano", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Gaviota": { "ubicacion": "Costa", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mito de Garganta Plateada": { "ubicacion": "Bosque (Puzzle de Salto)", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Serreta Chica": { "ubicacion": "Lago del Bosque", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paloma Zurita": { "ubicacion": "Área Central", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Charrán": { "ubicacion": "Costa del Este", "nivel": 7, "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tilopo de Wallace": { "ubicacion": "Campo de Flores (Campo del Molino)", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lavandera Blanca": { "ubicacion": "Playa Amatista", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Malvasía Cabeciblanca": { "ubicacion": "Montaña Onsen (Orilla del Lago)", "nivel": 9, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paloma de Wonga": { "ubicacion": "Bosque", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Alcaudón Común": { "ubicacion": "Suburbios", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Papamoscas de Vientre Amarillo": { "ubicacion": "Aldea de Pescadores (Muelle)", "nivel": 5, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] }
};

export const ANIMALES = {
  "Carpincho (Capibara)": { "ubicacion": "Ruinas en el área del círculo", "comida_favorita": ["Frambuesa", "Tomate", "Uva"], "clima_preferido": ["Lluvioso"] },
  "Ciervo": { "ubicacion": "Entre la Torre del Ciervo y el Pinar del Roble Espíritu", "comida_favorita": ["Lechuga", "Ensalada", "Rama"], "clima_preferido": ["Soleado"] },
  "Panda": { "ubicacion": "Puzzle de Salto", "comida_favorita": ["Bambú", "Manzana", "Maíz"], "clima_preferido": ["Lluvioso"] },
  "Nutria Marina": { "ubicacion": "Puerto de la Plaza de la Aldea de Pescadores", "comida_favorita": ["Ostra", "Camarón Común", "Camarón Oriental"], "clima_preferido": ["Lluvioso"] },
  "Alpaca": { "ubicacion": "Amatista cerca del puente de madera", "comida_favorita": ["Arándano", "Piña", "Trigo"], "clima_preferido": ["Soleado"] },
  "Zorro": { "ubicacion": "Debajo del Lago del Prado", "comida_favorita": ["Carne", "Perca Europea", "Perca Americana"], "clima_preferido": ["Arcoíris"] },
  "Conejito": { "ubicacion": "Camino de la Calle del Arte hacia los suburbios", "comida_favorita": ["Hierba", "Zanahoria", "Fresa"], "clima_preferido": ["Soleado"] },
  "Hurón": { "ubicacion": "Debajo del Río Rosado cerca del puente de madera", "comida_favorita": ["Huevo", "Lubina", "Gobio"], "clima_preferido": ["Arcoíris"] }
};

export const CULTIVOS = {
  "Papa": { "tiempo_crecimiento": "60 min", "nivel_jardineria": 1, "venta_semilla": 15, "compra_semilla": 30 },
  "Tomate": { "tiempo_crecimiento": "15 min", "nivel_jardineria": 1, "venta_semilla": 5, "compra_semilla": 10 },
  "Trigo": { "tiempo_crecimiento": "4 horas", "nivel_jardineria": 2, "venta_semilla": 47, "compra_semilla": 95 },
  "Lechuga": { "tiempo_crecimiento": "8 horas", "nivel_jardineria": 3, "venta_semilla": 72, "compra_semilla": 145 },
  "Piña": { "tiempo_crecimiento": "30 min", "nivel_jardineria": 4, "venta_semilla": 7, "compra_semilla": 15 },
  "Zanahoria": { "tiempo_crecimiento": "2 horas", "nivel_jardineria": 5, "venta_semilla": 25, "compra_semilla": 50 },
  "Fresa": { "tiempo_crecimiento": "6 horas", "nivel_jardineria": 6, "venta_semilla": 62, "compra_semilla": 125 },
  "Maíz": { "tiempo_crecimiento": "12 horas", "nivel_jardineria": 6, "venta_semilla": 85, "compra_semilla": 170 },
  "Uva": { "tiempo_crecimiento": "10 horas", "nivel_jardineria": 7, "venta_semilla": 80, "compra_semilla": 160 },
  "Berenjena": { "tiempo_crecimiento": "7 horas", "nivel_jardineria": 8, "venta_semilla": 13, "compra_semilla": 35 },
  "Árbol de Té": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 11, "venta_semilla": "N/A", "compra_semilla": 25 },
  "Cacao": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 12, "venta_semilla": "N/A", "compra_semilla": 110 },
  "Aguacate": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 13, "venta_semilla": "N/A", "compra_semilla": 180 },
  "Margarita": { "tiempo_crecimiento": "18 horas", "nivel_jardineria": 3, "venta_semilla": 15, "compra_semilla": 30 },
  "Pensamiento": { "tiempo_crecimiento": "18 horas", "nivel_jardineria": 4, "venta_semilla": 15, "compra_semilla": 30 },
  "Amapola": { "tiempo_crecimiento": "1 día", "nivel_jardineria": 5, "venta_semilla": 30, "compra_semilla": 60 },
  "Anturio": { "tiempo_crecimiento": "1 día", "nivel_jardineria": 5, "venta_semilla": 30, "compra_semilla": 60 },
  "Cala": { "tiempo_crecimiento": "1 día 6 horas", "nivel_jardineria": 6, "venta_semilla": 45, "compra_semilla": 90 },
  "Ipomoea": { "tiempo_crecimiento": "1 día 6 horas", "nivel_jardineria": 6, "venta_semilla": 45, "compra_semilla": 90 },
  "Clavel": { "tiempo_crecimiento": "1 día 6 horas", "nivel_jardineria": 7, "venta_semilla": 60, "compra_semilla": 120 },
  "Tulipán": { "tiempo_crecimiento": "2 días", "nivel_jardineria": 8, "venta_semilla": 75, "compra_semilla": 150 },
  "Lirio": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 9, "venta_semilla": "N/A", "compra_semilla": 200 },
  "Rosa": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 10, "venta_semilla": "N/A", "compra_semilla": 300 },
  "Jacinto": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 11, "venta_semilla": "N/A", "compra_semilla": 300 },
  "Orquídea Mariposa": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 12, "venta_semilla": "N/A", "compra_semilla": 300 },
  "Geranio": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 13, "venta_semilla": "N/A", "compra_semilla": 300 }
};

export const RECOLECTABLES = {
  "Rama": { "ubicacion": "Arbustos", "precio_venta": 5, "ganancia_energia": null },
  "Madera": { "ubicacion": "Árbol", "precio_venta": 6, "ganancia_energia": null },
  "Madera de Calidad": { "ubicacion": "Árbol", "precio_venta": 12, "ganancia_energia": null },
  "Madera Rara": { "ubicacion": "Árbol Gigante en los Suburbios", "precio_venta": 50, "ganancia_energia": null },
  "Madera de Roble Errante": { "ubicacion": "Roble Errante", "precio_venta": 150, "ganancia_energia": null },
  "Bambú": { "ubicacion": "Bambú", "precio_venta": 7, "ganancia_energia": null },
  "Piedra": { "ubicacion": "Hogar", "precio_venta": 8, "ganancia_energia": null },
  "Mineral": { "ubicacion": "Hogar", "precio_venta": 14, "ganancia_energia": null },
  "Fluorita Impecable": { "ubicacion": "Mina de Fluorita", "precio_venta": 150, "ganancia_energia": null },
  "Fragmento de Estrella": { "ubicacion": "Lluvia de Meteoritos (Mineral de Meteorito)", "precio_venta": 150, "ganancia_energia": null },
  "Manzana": { "ubicacion": "Hogar", "precio_venta": 2, "ganancia_energia": 88 },
  "Mandarina": { "ubicacion": "Hogar", "precio_venta": 2, "ganancia_energia": 88 },
  "Arándano Azul": { "ubicacion": "Hogar", "precio_venta": 1, "ganancia_energia": 65 },
  "Frambuesa": { "ubicacion": "Hogar", "precio_venta": 2, "ganancia_energia": 67 },
  "Shiitake": { "ubicacion": "Aldea de Pescadores", "precio_venta": 1, "ganancia_energia": 65 },
  "Shiitake Extraño (Negro)": { "ubicacion": "Aldea de Pescadores", "precio_venta": 16, "ganancia_energia": null },
  "Champiñón de París": { "ubicacion": "Campo de Flores", "precio_venta": 1, "ganancia_energia": 65 },
  "Boleto (Penny Bun)": { "ubicacion": "Bosque", "precio_venta": 1, "ganancia_energia": 65 },
  "Gírgola (Oyster Mushroom)": { "ubicacion": "Montaña Onsen", "precio_venta": 1, "ganancia_energia": 65 },
  "Trufa Negra": { "ubicacion": "Bosque (Isla del Bosque)", "precio_venta": 99, "ganancia_energia": 25 },
  "Matsutake": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "precio_venta": 5, "ganancia_energia": null }
};

export const HABITANTES = {
  "Doris": { 
    "rol": "Comerciante Estelar", 
    "imagen": "/npc/doris-rain.webp", 
    "descripcion": "Versión Meteorito (intercambio de fragmentos por muebles estelares) o Versión Lluvia (receta exclusiva de azúcar).", 
    "ubicacion": "Variable según el clima" 
  },
  "Albert Jr": { 
    "rol": "Comerciante", 
    "imagen": "/npc/albert-jr.webp", 
    "descripcion": "Comerciante que te permite vender tu excedente por monedas de oro.", 
    "ubicacion": "Centro del pueblo" 
  },
  "Señora Joan": { 
    "rol": "Animal Mistress", 
    "imagen": "/npc/mrs-joan.webp", 
    "descripcion": "Tienda de comida y complementos para perros/gatos.", 
    "ubicacion": "Tienda de mascotas" 
  },
  "Bailey J": { 
    "rol": "Especialista en Aves", 
    "imagen": "/npc/bailey-j.webp",  
    "descripcion": "Recompensas y evento 'Regreso al nido'.", 
    "ubicacion": "Campo de Flores" 
  },
  "Annie": { 
    "rol": "Tienda de Música",   
    "imagen": "/npc/annie.webp",   
    "descripcion": "Tienda de música, instrumentos y entretenimiento.",   
    "ubicacion": "Tienda de música" 
  },
  "Dorothee": { 
    "rol": "Diseñadora de Moda", 
    "imagen": "/npc/dorothee.webp", 
    "descripcion": "Tienda de ropa que cambia todos los días.", 
    "ubicacion": "Boutique"
  },
  "Bob": { 
    "rol": "Artesano", 
    "imagen": "/npc/bob.webp", 
    "descripcion": "El abuelo manitas de muebles construidos de forma natural.", 
    "ubicacion": "Taller de carpintería" 
  },
  "Blanc": { 
    "rol": "Jardinero Experto", 
    "imagen": "/npc/blanc.webp", 
    "descripcion": "Experto en jardinería (semillas de flores y hortalizas).", 
    "ubicacion": "Invernadero" 
  },
  "Massimo": { 
    "rol": "Chef", 
    "imagen": "/npc/massimo.webp",   
    "descripcion": "Chef (recetas y equipamiento de cocina).",  
    "ubicacion": "Restaurante" 
  },
  "Vanya": { 
    "rol": "Experta en Pesca", 
    "imagen": "/npc/vanya.webp",   
    "descripcion": "Experta en pesca (equipos y acuarios).",  
    "ubicacion": "Muelle" 
  },
  "Naniwa": { 
    "rol": "Entomóloga",  
    "imagen": "/npc/naniwa.webp",   
    "descripcion": "Vivarios, burbujas y eventos de caza de insectos.",  
    "ubicacion": "Laboratorio"
  },
  "Andrew": { 
    "rol": "Biker",   
    "imagen": "/npc/andrew.webp",   
    "descripcion": "Biker para facilitar tus viajes rápidos.",   
    "ubicacion": "Estación de transporte"
  },
  "Bill": { 
    "rol": "Capitán",  
    "imagen": "/npc/bill.webp",   
    "descripcion": "Responsable del evento 'Pesca en el mar en barco'.",   
    "ubicacion": "Puerto"
  }
};

export const RECETAS = {
  "Ensalada de Campo": { "ingredientes": "Cualquier tipo de verduras x2", "valor": 90, "rareza": "Común" },
  "Mermelada Surtida": { "ingredientes": "Cualquier tipo de frutas x4", "valor": 160, "rareza": "Común" },
  "Mermelada de Frambuesa": { "ingredientes": "Frambuesas x4", "valor": 250, "rareza": "Común" },
  "Salsa de Tomate": { "ingredientes": "Tomates x4", "valor": 180, "rareza": "Común" },
  "Mermelada de Arándano": { "ingredientes": "Arándanos x4", "valor": 170, "rareza": "Común" },
  "Mermelada de Manzana": { "ingredientes": "Manzanas x4", "valor": 270, "rareza": "Común" },
  "Mermelada de Naranja": { "ingredientes": "Naranjas x4", "valor": 270, "rareza": "Común" },
  "Mermelada de Uva": { "ingredientes": "Uvas x4", "valor": null, "rareza": "Común" },
  "Mermelada de Fresa": { "ingredientes": "Fresas x4", "valor": 1580, "rareza": "Común" },
  "Pescado con Patatas": { "ingredientes": "Pescados x2, Patatas x2", "valor": 310, "rareza": "Común" },
  "Comida Extraña": { "ingredientes": "Fallar cualquier plato", "valor": 30, "rareza": "Común" },
  "Mermelada de Piña": { "ingredientes": "Piñas x4", "valor": 280, "rareza": "Común" },
  "Champiñones Asados": { "ingredientes": "Cualquier tipo de champiñones x4", "valor": 180, "rareza": "Común" },
  "Setas Ostra Asadas": { "ingredientes": "Setas Ostra x4", "valor": 180, "rareza": "Común" },
  "Shiitake Asado": { "ingredientes": "Shiitake x4", "valor": 180, "rareza": "Común" },
  "Champiñones de París Asados": { "ingredientes": "Champiñones de París x2", "valor": 180, "rareza": "Común" },
  "Boletos Asados": { "ingredientes": "Boletos x2", "valor": 180, "rareza": "Común" },
  "Salsa de Chocolate": { "ingredientes": "Cacao x4", "valor": null, "rareza": "Común" },
  "Tarta de Queso": { "ingredientes": "Queso x1, Leche x1, Trigo x1", "valor": 480, "rareza": "Común" },
  "Rollo de Nubes Flotantes Original": { "ingredientes": "Huevo x1, Leche x1, Azúcar de cualquier color x2", "valor": 550, "rareza": "Común" },
  "Rollo de Nubes Flotantes Rojo": { "ingredientes": "Huevo x1, Leche x1, Azúcar rojo x2", "valor": 670, "rareza": "Común" },
  "Rollo de Nubes Flotantes Naranja": { "ingredientes": "Huevo x1, Leche x1, Azúcar naranja x2", "valor": null, "rareza": "Común" },
  "Rollo de Nubes Flotantes Amarillo": { "ingredientes": "Huevo x1, Leche x1, Azúcar amarillo x2", "valor": 570, "rareza": "Común" },
  "Rollo de Nubes Flotantes Violeta": { "ingredientes": "Huevo x1, Leche x1, Azúcar violeta x2", "valor": 570, "rareza": "Común" },
  "Rollo de Nubes Flotantes Verde": { "ingredientes": "Huevo x1, Leche x1, Azúcar verde x2", "valor": null, "rareza": "Común" },
  "Rollo de Nubes Flotantes Cian": { "ingredientes": "Huevo x1, Leche x1, Azúcar cian x2", "valor": 570, "rareza": "Común" },
  "Rollo de Nubes Flotantes Azul": { "ingredientes": "Huevo x1, Leche x1, Azúcar azul x2", "valor": 570, "rareza": "Común" },
  "Tarta de Champiñones": { "ingredientes": "Champiñones x2, Trigo x1, Huevo x1", "valor": 500, "rareza": "Común" },
  "Tarta de Setas Ostra": { "ingredientes": "Setas Ostra x2, Trigo x1, Huevo x1", "valor": 500, "rareza": "Común" },
  "Tarta de Shiitake": { "ingredientes": "Shiitake x2, Trigo x1, Huevo x1", "valor": 500, "rareza": "Común" },
  "Tarta de Champiñón de París": { "ingredientes": "Champiñones de París x2, Trigo x1, Huevo x1", "valor": 500, "rareza": "Común" },
  "Tarta de Boletos": { "ingredientes": "Boletos x2, Trigo x1, Huevo x1", "valor": 500, "rareza": "Común" },
  "Tarta de Trufa Negra": { "ingredientes": "Trufas negras x2, Trigo x1, Huevo x1", "valor": 830, "rareza": "Común" },
  "Café": { "ingredientes": "Granos de café x4", "valor": 290, "rareza": "Común" },
  "Café con Leche": { "ingredientes": "Granos de café x2, Leche x2", "valor": 300, "rareza": "Común" },
  "Bebida Extraña": { "ingredientes": "Fallar cualquier bebida", "valor": 30, "rareza": "Común" },
  "Bagel de Pescado Ahumado": { "ingredientes": "Pescados x1, Queso x1, Verduras x1, Trigo x1", "valor": 520, "rareza": "Común" },
  "Risotto de Mariscos": { "ingredientes": "Mariscos x2, Trigo x1, Tomate x1", "valor": 490, "rareza": "Común" },
  "Guiso Rústico": { "ingredientes": "Tomates x1, Patatas x1, Lechuga x1", "valor": 640, "rareza": "Común" },
  "Pasta con Crema de Trufa Negra": { "ingredientes": "Trufas negras x1, Trigo x2, Leche x1", "valor": 900, "rareza": "Común" },
  "Pizza de Mariscos": { "ingredientes": "Queso x1, Salsa de tomate x1, Trigo x1, Pescado x1", "valor": 780, "rareza": "Común" },
  "Espagueti Boloñesa": { "ingredientes": "Carne x1, Trigo x1, Tomate x1, Queso x1", "valor": 670, "rareza": "Común" }
};

export const LOGROS = {
  "Nunca con las manos vacías": { "requisito": "Nivel 10 en el hobby de Pesca", "titulo": "Pescador Místico", "nota": "Skilled Angler", "imagen": "/logros/never-empty-handed.webp" },
  "Pescador Místico": { "requisito": "Activa la fase oculta del Evento de Pesca 10 veces en total", "titulo": "Pescador", "nota": "Fisher", "imagen": "/logros/mystic-fisher.webp" },
  "Bendición del Cardumen": { "requisito": "Activa 100 cardúmenes en total durante eventos de pesca", "titulo": "Bendición", "nota": "Blessing", "imagen": "/logros/shoals-blessing.webp" },
  "Marinero Fuerte": { "requisito": "Atrapa peces de más de 100kg por 2 veces consecutivas", "titulo": "Sedal de Pesca", "nota": "Fishing Line", "imagen": "/logros/strong-sailor.webp" },
  "Fortuna de Peces Gemelos": { "requisito": "Atrapa 2 peces de 5 estrellas en menos de 1 minuto", "titulo": "Águila Pescadora", "nota": "Osprey", "imagen": "/logros/twin-fish-fortune.webp" },
  "Máquina de Pesca": { "requisito": "Atrapa un total de 50 peces de más de 100kg cada uno", "titulo": "Cesta de Peces", "nota": "Fish Basket", "imagen": "/logros/fishing-machine.webp" },
  "Frenesí de Tiburones": { "requisito": "Atrapa 3 tiburones de sombras doradas en un solo evento de pesca marina", "titulo": "Jaula de Tiburones", "nota": "Shark Cage", "imagen": "/logros/shark-frenzy.webp" },
  "Invocador de Cardúmenes": { "requisito": "Activa 3 cardúmenes en un solo evento de pesca", "titulo": "Invocador de Cardúmenes", "nota": "Shoal Caller", "imagen": "/logros/shoal-caller.webp" },
  "Pescador de Luz Estelar": { "requisito": "Atrapa 4 peces de 5 estrellas en un solo evento de pesca", "titulo": "Maníaco de la Pesca", "nota": "Fishing Maniac", "imagen": "/logros/starlight-fisher.webp" },
  "Leyenda de la Cocina del Pueblo": { "requisito": "Nivel 10 en el hobby de Cocina", "titulo": "Chef", "nota": "Chef", "imagen": "/logros/town-cooking-legend.webp" },
  "Rápido y Perfecto": { "requisito": "Cocina 2 platos de 5 estrellas en menos de 60 segundos", "titulo": "Reloj de Cocina", "nota": "Kitchen Clock", "imagen": "/logros/fast-and-lawless.webp" },
  "Toque Verde": { "requisito": "Nivel 10 en el hobby de Jardinería", "titulo": "Horticultor", "nota": "Horticulturist", "imagen": "/logros/green-touch.webp" },
  "Cosecha Abundante": { "requisito": "Cosecha cultivos de 5 estrellas mientras la Cosecha de Bonificación está activa", "titulo": "Cosecha", "nota": "Harvest", "imagen": "/logros/plentiful-harvest.webp" },
  "Suerte del Arcoíris": { "requisito": "Activa 2 bendiciones híbridas de arcoíris en un solo riego de área múltiple", "titulo": "Suerte del Arcoíris", "nota": "Rainbow Luck", "imagen": "/logros/rainbow-luck.webp" },
  "Sirviente Gatuno Ace": { "requisito": "Nivel 10 en el hobby de Cuidado de Gatos", "titulo": "Amante de los Gatos", "nota": "Cat Lover", "imagen": "/logros/ace-cat-servant.webp" },
  "Cantina Miau-Miau": { "requisito": "Alimenta a 5 gatos con su comida favorita", "titulo": "Comida para Gatos", "nota": "Cat Food", "imagen": "/logros/meow-meow-canteen.webp" },
  "Entrenador de Perros Ace": { "requisito": "Nivel 10 en el hobby de Cuidado de Perros", "titulo": "Amigo de los Perros", "nota": "Dog Pal", "imagen": "/logros/ace-dog-trainer.webp" },
  "Cantina Perruna": { "requisito": "Alimenta a 3 perros con su comida favorita", "titulo": "Comida para Perros", "nota": "Dog Food", "imagen": "/logros/doggie-canteen.webp" },
  "Comandante de Insectos": { "requisito": "Nivel 10 en el hobby de Captura de Insectos", "titulo": "Maestro de Insectos", "nota": "Insect Master", "imagen": "/logros/insect-commander.webp" },
  "Rastreador Místico": { "requisito": "Activa la fase oculta del evento de captura de insectos 10 veces", "titulo": "Exploración", "nota": "Exploration", "imagen": "/logros/mystic-tracker.webp" },
  "Recolector de Insectos": { "requisito": "Atrapa 3 insectos con una sola burbuja de captura", "titulo": "Triple Captura", "nota": "Triple Catch", "imagen": "/logros/insect-harvester.webp" },
  "Susurrador de Aves": { "requisito": "Nivel 10 en el hobby de Avistamiento de Aves", "titulo": "Susurrador de Aves", "nota": "Bird Whisperer", "imagen": "/logros/bird-whisperer.webp" },
  "Caminante de Nubes": { "requisito": "Activa la fase oculta del evento de aves 10 veces", "titulo": "Cielo", "nota": "Sky", "imagen": "/logros/cloud-walker.webp" },
  "Artista de Esculturas de Arena": { "requisito": "Nivel 5 en el hobby de Esculturas de Arena", "titulo": "Escultor de Arena", "nota": "Sand Sculptor", "imagen": "/logros/sand-sculpture-artist.webp" },
  "Patrocinador de Cohetes": { "requisito": "Gana un total de 500,000 de Oro vendiendo a Albert Jr.", "titulo": "Cohete", "nota": "Rocket", "imagen": "/logros/rocket-sponsor.webp" },
  "Miembro D.G.": { "requisito": "Alcanza el nivel 30 de Miembro D.G.", "titulo": "Miembro D.G.", "nota": "D.G. Member", "imagen": null },
  "Vecino Animal": { "requisito": "Alcanza el nivel 10 de vínculo con 8 grupos de animales", "titulo": "Nuevo Vecino", "nota": "New Neighbour", "imagen": "/logros/animal-neighbors.webp" },
  "Guardián de Animales": { "requisito": "Descubre la comida favorita de 8 grupos de animales", "titulo": "Delicioso", "nota": "Delicious", "imagen": "/logros/animal-sitter.webp" },
  "Experto en Reparaciones": { "requisito": "Comparte kits de reparación con 100 miembros D.G. en total", "titulo": "Reparaciones", "nota": "Repairs", "imagen": "/logros/repair-expert.webp" },
  "Estrella del Pop": { "requisito": "Recibe un total de 100 Likes en tu casa", "titulo": "Estrella Naciente", "nota": "Rising Star", "imagen": "/logros/star.webp" },
  "Compañero de Onsen": { "requisito": "Toma un baño termal con amigos", "titulo": "Onsen", "nota": "Onsen", "imagen": "/logros/friends-of-the-hot-springs.webp" },
  "Bajo la Lluvia de Meteoritos": { "requisito": "Pide un deseo bajo un meteorito con amigos", "titulo": "Géminis", "nota": "Gemini", "imagen": null }
};

export const CATEGORIES = [
  { id: 'peces', name: 'Peces', icon: 'Fish', description: 'Guía completa de pesca', count: Object.keys(PECES).length },
  { id: 'insectos', name: 'Insectos', icon: 'Bug', description: 'Captura de insectos', count: Object.keys(INSECTOS).length },
  { id: 'aves', name: 'Aves', icon: 'Bird', description: 'Avistamiento de aves', count: Object.keys(AVES).length },
  { id: 'animales', name: 'Animales', icon: 'Paw', description: 'Animales salvajes', count: Object.keys(ANIMALES).length },
  { id: 'cultivos', name: 'Cultivos', icon: 'Leaf', description: 'Jardinería y flores', count: Object.keys(CULTIVOS).length },
  { id: 'recolectables', name: 'Recolectables', icon: 'TreeDeciduous', description: 'Recursos del mundo', count: Object.keys(RECOLECTABLES).length },
  { id: 'habitantes', name: 'Habitantes', icon: 'Users', description: 'NPCs del pueblo', count: Object.keys(HABITANTES).length },
  { id: 'recetas', name: 'Recetas', icon: 'ChefHat', description: 'Cocina y comida', count: Object.keys(RECETAS).length },
  { id: 'logros', name: 'Logros', icon: 'Trophy', description: 'Títulos y logros', count: Object.keys(LOGROS).length },
];

export type CategoryId = 'peces' | 'insectos' | 'aves' | 'animales' | 'cultivos' | 'recolectables' | 'habitantes' | 'recetas' | 'logros';

export function getCategoryData(categoryId: CategoryId) {
  switch (categoryId) {
    case 'peces': return PECES;
    case 'insectos': return INSECTOS;
    case 'aves': return AVES;
    case 'animales': return ANIMALES;
    case 'cultivos': return CULTIVOS;
    case 'recolectables': return RECOLECTABLES;
    case 'habitantes': return HABITANTES;
    case 'recetas': return RECETAS;
    case 'logros': return LOGROS;
    default: return {};
  }
}
