// Heartopia Wiki Data

export const PECES = {
  "Coregono": { "ubicacion": "Mar de Céfiro", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Barbo Común": { "ubicacion": "Río Poco Profundo", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Alburno": { "ubicacion": "Lago", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Perca Europea": { "ubicacion": "Río", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cacho": { "ubicacion": "Lago", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Locha de Espina": { "ubicacion": "Río del Bosque Gigante", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pequeño Pez de Río": { "ubicacion": "Río Tranquilo", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tenca": { "ubicacion": "Lago del Bosque", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Carpa Gibelio": { "ubicacion": "Lago", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Schneider": { "ubicacion": "Lago Suburbano", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Sardina": { "ubicacion": "Océano", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lubina": { "ubicacion": "Océano", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Camarón Oriental": { "ubicacion": "Río", "nivel": 1, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Listado": { "ubicacion": "Océano", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Sable": { "ubicacion": "Mar de Céfiro", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Camarón Común": { "ubicacion": "Mar del Este", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Jurel": { "ubicacion": "Mar de la Ballena", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Espinoso Marino": { "ubicacion": "Mar Viejo", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Salmonete de Roca": { "ubicacion": "Pesca Marina", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Eperlán Europeo": { "ubicacion": "Lago de la Pradera", "nivel": 1, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Caballito de Mar": { "ubicacion": "Mar de la Ballena", "nivel": 1, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día"] },
  "Pulpo Común": { "ubicacion": "Pesca Marina", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Locha de Piedra": { "ubicacion": "Lago Suburbano", "nivel": 2, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Jurel Falso": { "ubicacion": "Mar de Céfiro", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Abisal": { "ubicacion": "Pesca Marina", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pulpo Pigmeo del Atlántico": { "ubicacion": "Mar de la Ballena", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Rodaballo": { "ubicacion": "Pesca Marina", "nivel": 2, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lubina Negra": { "ubicacion": "Lago del Bosque", "nivel": 2, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Salmón del Atlántico": { "ubicacion": "Mar de la Ballena", "nivel": 3, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Pez Payaso": { "ubicacion": "Mar Viejo", "nivel": 3, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lucioperca": { "ubicacion": "Río del Bosque Gigante", "nivel": 3, "tipo": "Río", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Acerina": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 3, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Rana Comestible": { "ubicacion": "Lagos", "nivel": 3, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cangrejo Ermitaño": { "ubicacion": "Mar del Este", "nivel": 3, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Sol del Fango": { "ubicacion": "Lago del Bosque", "nivel": 3, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Tilapia": { "ubicacion": "Ríos", "nivel": 3, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Streber": { "ubicacion": "Río Rosado", "nivel": 3, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cangrejo de Río Europeo": { "ubicacion": "Lago del Bosque", "nivel": 3, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche", "Amanecer"] },
  "Carpa Común": { "ubicacion": "Río Rosado", "nivel": 4, "tipo": "Río", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Lota": { "ubicacion": "Río Tranquilo", "nivel": 4, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Día"] },
  "Solla": { "ubicacion": "Mar Viejo", "nivel": 4, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche", "Amanecer"] },
  "Gobio": { "ubicacion": "Mar del Este", "nivel": 4, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer", "Amanecer"] },
  "Mejillón": { "ubicacion": "Lago Suburbano", "nivel": 4, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Conejo": { "ubicacion": "Océano", "nivel": 4, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cangrejo de Río": { "ubicacion": "Lago Suburbano", "nivel": 4, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Renacuajo": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 4, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Trucha": { "ubicacion": "Lago de la Pradera", "nivel": 5, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche", "Amanecer"] },
  "Koi Mariposa": { "ubicacion": "Lago de la Pradera", "nivel": 5, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Caballa del Atlántico": { "ubicacion": "Mar de la Ballena", "nivel": 5, "tipo": "Mar", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Rutilo": { "ubicacion": "Lago Suburbano", "nivel": 5, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Calamar Volador Europeo": { "ubicacion": "Pesca Marina", "nivel": 5, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Langosta Europea": { "ubicacion": "Mar de Céfiro", "nivel": 5, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Blenio de Agua Dulce": { "ubicacion": "Río Rosado", "nivel": 5, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Piraña de Vientre Rojo": { "ubicacion": "Río del Bosque Gigante", "nivel": 5, "tipo": "Río", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Salmón Keta": { "ubicacion": "Río Tranquilo", "nivel": 6, "tipo": "Río", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tímalo": { "ubicacion": "Lago Suburbano", "nivel": 6, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mejillón de Perla Grande": { "ubicacion": "Lago del Bosque", "nivel": 6, "tipo": "Lago", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lija": { "ubicacion": "Pesca Marina", "nivel": 6, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Globo": { "ubicacion": "Mar Viejo", "nivel": 6, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Rubio": { "ubicacion": "Mar del Este", "nivel": 6, "tipo": "Mar", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Besugo": { "ubicacion": "Mar de Céfiro", "nivel": 7, "tipo": "Mar", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Atardecer"] },
  "Anguila Europea": { "ubicacion": "Mar Viejo", "nivel": 7, "tipo": "Mar", "clima": ["Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Fartet del Mediterráneo": { "ubicacion": "Lago Suburbano", "nivel": 7, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Pez Remo Gigante": { "ubicacion": "Pesca Marina", "nivel": 7, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Esculpin Moteado": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 7, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Espinoso": { "ubicacion": "Río Poco Profundo", "nivel": 7, "tipo": "Río", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cangrejo de Río Azul": { "ubicacion": "Lago del Bosque", "nivel": 8, "tipo": "Lago", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Umbra Europea": { "ubicacion": "Lago Suburbano", "nivel": 8, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer"] },
  "Cangrejo Real Dorado": { "ubicacion": "Pesca Marina", "nivel": 8, "tipo": "Mar", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Dorado": { "ubicacion": "Lago de la Pradera", "nivel": 8, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Atún de Aleta Azul": { "ubicacion": "Pesca Marina", "nivel": 9, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Huchón": { "ubicacion": "Río del Bosque Gigante", "nivel": 9, "tipo": "Río", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Luna": { "ubicacion": "Pesca Marina", "nivel": 9, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer"] },
  "Lucio del Norte": { "ubicacion": "Lago Suburbano", "nivel": 9, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Luna Gigante": { "ubicacion": "Mar del Este", "nivel": 9, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Sol": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 9, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Trucha Ártica": { "ubicacion": "Lago del Bosque", "nivel": 10, "tipo": "Lago", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Agalla Azul": { "ubicacion": "Lago de la Montaña Onsen", "nivel": 10, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Tiburón Mako": { "ubicacion": "Pesca Marina", "nivel": 10, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pez Espada": { "ubicacion": "Pesca Marina", "nivel": 10, "tipo": "Mar", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Siluro": { "ubicacion": "Lago de la Pradera", "nivel": 10, "tipo": "Lago", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Pargo": { "ubicacion": "Mar de Céfiro", "nivel": 10, "tipo": "Mar", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Cangrejo Real": { "ubicacion": "Mar de la Ballena", "nivel": 10, "tipo": "Mar", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] }
};

export const INSECTOS = {
  "Escarabajo Longicornio Alpino": { "ubicacion": "Isla del Bosque", "nivel": 5, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo de la Flor Amatista": { "ubicacion": "Hogar (Rocas)", "nivel": 2, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Hormiga": { "ubicacion": "Aldea de Pescadores (Plaza)", "nivel": 3, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Apolo": { "ubicacion": "Evento Cebo para Insectos", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mariquita Asiática": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 5, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Escarabajo del Espárrago": { "ubicacion": "Campo de Flores", "nivel": 1, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Polilla del Cesto": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 10, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Demoiselle Hermosa": { "ubicacion": "Orilla del Lago del Bosque", "nivel": 6, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Leopardo Hermoso": { "ubicacion": "Aldea de Pescadores (Muelle)", "nivel": 4, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Atardecer"] },
  "Morpho Azul": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 7, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Chinche de Escudo Azul": { "ubicacion": "Aldea de Pescadores (Faro)", "nivel": 6, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Abejorro": { "ubicacion": "Campo de Flores", "nivel": 2, "tipo": "Abeja", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Blanquita de la Col": { "ubicacion": "Aldea de Pescadores", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Carpintera Cerúlea": { "ubicacion": "Aldea de Pescadores (Plaza)", "nivel": 9, "tipo": "Abeja", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Tigre de Castaño": { "ubicacion": "Evento Cebo para Insectos", "nivel": 7, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cigarra": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 4, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Día", "Atardecer"] },
  "Polilla Cometa": { "ubicacion": "Suburbios", "nivel": 8, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Mariposa Azul Común": { "ubicacion": "Área Central", "nivel": 2, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Limonera Común": { "ubicacion": "Suburbios", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Libélula de Cola Blanca": { "ubicacion": "Ribera del Río", "nivel": 4, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mantis de Cabeza de Cono": { "ubicacion": "Montaña Onsen (Ruinas)", "nivel": 9, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Planeador de Pantano Carmesí": { "ubicacion": "Montaña Onsen", "nivel": 7, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Noche", "Día", "Atardecer"] },
  "Escarabajo de la Flor Elegante": { "ubicacion": "Campo de Flores (Montaña Ballena)", "nivel": 7, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Chinche de la Mezquita": { "ubicacion": "Hogar (Rocas)", "nivel": 1, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo de Color Fuego": { "ubicacion": "Montaña Onsen (Onsen)", "nivel": 3, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mariquita de Cuatro Manchas": { "ubicacion": "Montaña Onsen (Lago del Cráter)", "nivel": 4, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Libélula de Cuatro Manchas": { "ubicacion": "Lakeshore Suburbano", "nivel": 2, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mantis Gigante Asiática": { "ubicacion": "Montaña Onsen (Ruinas)", "nivel": 5, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Saltamontes de Oro": { "ubicacion": "Montaña Onsen", "nivel": 1, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo Joya Dorado": { "ubicacion": "Bosque (Puzzle de Salto)", "nivel": 7, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Escarabajo Ciervo Dorado": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 9, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Ala de Pájaro Verde": { "ubicacion": "Suburbios", "nivel": 6, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Escarabajo Tigre Verde": { "ubicacion": "Montaña Onsen", "nivel": 2, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo Hércules": { "ubicacion": "Montaña Onsen (Lago del Cráter)", "nivel": 10, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Escarabajo Cornudo": { "ubicacion": "Aldea de Pescadores (Muelle Este)", "nivel": 8, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Katídido": { "ubicacion": "Campo de Flores (Playa Amatista)", "nivel": 3, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Saltamontes de Bandas Grandes": { "ubicacion": "Suburbios", "nivel": 4, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Atardecer", "Noche"] },
  "Libélula Roja Grande": { "ubicacion": "Orilla del Agua", "nivel": 1, "tipo": "Libélula", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mantis Mediterránea": { "ubicacion": "Montaña Onsen (Acantilado de Piedra)", "nivel": 4, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer", "Noche"] },
  "Mini Polilla Luna": { "ubicacion": "Suburbios", "nivel": 3, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Escarabajo Minotauro": { "ubicacion": "Montaña Onsen (Ruinas)", "nivel": 7, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día"] },
  "Morpho Helena": { "ubicacion": "Campo de Flores (Playa Amatista)", "nivel": 10, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Madreperla": { "ubicacion": "Campo de Flores (Campo del Molino)", "nivel": 9, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer"] },
  "Manto de Luto": { "ubicacion": "Montaña Onsen (Onsen)", "nivel": 5, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día"] },
  "Macaón del Viejo Mundo": { "ubicacion": "Bosque", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Punta Naranja": { "ubicacion": "Área Central", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mariposa Pavo Real": { "ubicacion": "Campo de Flores (Campo del Molino)", "nivel": 5, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Chinche Picasso": { "ubicacion": "Campo de Flores (Playa Amatista)", "nivel": 8, "tipo": "Bicho", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Atardecer"] },
  "Katídido Rosa": { "ubicacion": "Evento Cebo para Insectos", "nivel": 3, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mariposa Cartero": { "ubicacion": "Evento Cebo para Insectos", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Emperador Púrpura": { "ubicacion": "Campo de Flores (Montaña Ballena)", "nivel": 3, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Día", "Atardecer"] },
  "Escarabajo Ciervo Arcoíris": { "ubicacion": "Evento Cebo para Insectos (Ruinas)", "nivel": 9, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Ala de Pájaro de Rajah Brooke": { "ubicacion": "Hogar", "nivel": 3, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Atardecer"] },
  "Mariquita de Siete Puntos": { "ubicacion": "Suburbios", "nivel": 2, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Saltamontes Siberiano": { "ubicacion": "Aldea de Pescadores", "nivel": 2, "tipo": "Saltamontes", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo Joya de Plata": { "ubicacion": "Acantilado Onsen (Lado de árboles)", "nivel": 6, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día"] },
  "Polilla Luna Española": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 8, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Día", "Atardecer"] },
  "Carpintera de Patas Desparramadas": { "ubicacion": "Campo de Flores (Montaña Ballena)", "nivel": 5, "tipo": "Abeja", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Escarabajo Ciervo": { "ubicacion": "Bosque (Puzzle de Salto)", "nivel": 6, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Morpho de Sulkowsky": { "ubicacion": "Atractor de Insectos Inflable Especial", "nivel": 1, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Morpho del Atardecer": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 10, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Amanecer", "Día"] },
  "Abeja Cuco de Waroona": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 3, "tipo": "Abeja", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Amanecer", "Día", "Atardecer"] },
  "Escarabajo Avispa": { "ubicacion": "Bosque", "nivel": 2, "tipo": "Escarabajo", "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Bruja Blanca": { "ubicacion": "Evento Cebo para Insectos", "nivel": 5, "tipo": "Mariposa", "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] }
};

export const AVES = {
  "Paloma de Oliva Africana": { "ubicacion": "Montaña Onsen (Onsen)", "nivel": 5, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Flamenco Americano": { "ubicacion": "Campo de Flores", "nivel": 9, "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Día"] },
  "Gaviota de Audouin": { "ubicacion": "Mar Ballena (Costas y playas), Playa Amatista", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Herrerillo Azur": { "ubicacion": "Campo de Flores (Campo del Molino)", "nivel": 7, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Bigotudo": { "ubicacion": "Montaña Onsen", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pavo Real Azul": { "ubicacion": "Evento Nido de Cientos", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Guacamayo Azul y Amarillo": { "ubicacion": "Evento Nido de Cientos", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tiñosa Parda": { "ubicacion": "Costa del Mar Antiguo", "nivel": 5, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paloma Terrestre Canela": { "ubicacion": "Aldea de Pescadores (Muelle Este)", "nivel": 6, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cernícalo Vulgar": { "ubicacion": "Bosque (Torre del Ciervo)", "nivel": 7, "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pinzón de Doble Barra": { "ubicacion": "Aldea de Pescadores (Faro)", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Azulejo de las Montañas": { "ubicacion": "Suburbios", "nivel": 8, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Camachuelo Común": { "ubicacion": "Suburbios", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Pinzón Vulgar": { "ubicacion": "Campo de Flores", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tórtola Turca": { "ubicacion": "Hogar", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Oropéndola Europea": { "ubicacion": "Río Rosado, Hogar", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Trepador Azul": { "ubicacion": "Aldea de Pescadores", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Silbón Europeo": { "ubicacion": "Río", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Chochín Común": { "ubicacion": "Bosque", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Abejaruco Europeo": { "ubicacion": "Montaña Onsen (Orilla del Lago)", "nivel": 5, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Petirrojo Europeo": { "ubicacion": "Área Central", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cormorán Moñudo": { "ubicacion": "Océano", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Guacamayo Verde Mayor": { "ubicacion": "Evento Nido de Cientos", "nivel": 5, "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Carbonero Común": { "ubicacion": "Montaña Onsen", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Flamenco Mayor": { "ubicacion": "Orilla del Agua", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Picogordo": { "ubicacion": "Montaña Onsen (Lago del Cráter)", "nivel": 6, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Atardecer"] },
  "Cormorán Imperial": { "ubicacion": "Mar del Este / Mar Céfiro", "nivel": 9, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tilopo de Jambu": { "ubicacion": "Suburbios", "nivel": 7, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Eider Real": { "ubicacion": "Río", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Faisán de Lady Amherst": { "ubicacion": "Montaña Onsen (Ruinas)", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Guacamayo de Lear": { "ubicacion": "Evento Nido de Cientos", "nivel": 7, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Flamenco Menor": { "ubicacion": "Orilla del Lago del Bosque", "nivel": 5, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Búho Chico": { "ubicacion": "Montaña Onsen (Acantilado de Piedra)", "nivel": 6, "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mito de Buscapies": { "ubicacion": "Sobre la cabeza de Blanc", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Ánade Real": { "ubicacion": "Lago", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tangara Siete Colores": { "ubicacion": "Suburbios", "nivel": 9, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Halcón Peregrino": { "ubicacion": "Montaña Onsen (Onsen)", "nivel": 7, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Dúcula Imperial": { "ubicacion": "Aldea de Pescadores", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Camachuelo de los Pinos": { "ubicacion": "Isla del Bosque", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paloma Rosa": { "ubicacion": "Campo de Flores (Montaña Ballena)", "nivel": 7, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Vinago Cuellirrojo": { "ubicacion": "Campo de Flores", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paradoxorn de Przevalski": { "ubicacion": "Aldea de Pescadores (Plaza)", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Cormorán Carirrojo": { "ubicacion": "Mar Antiguo / Mar Ballena", "nivel": 6, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Guacamayo Rojo y Verde": { "ubicacion": "Evento Nido de Cientos", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Ave de Regente": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tarro Canelo": { "ubicacion": "Lago Suburbano", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Gaviota": { "ubicacion": "Costa", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Mito de Garganta Plateada": { "ubicacion": "Bosque (Puzzle de Salto)", "nivel": 3, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Serreta Chica": { "ubicacion": "Lago del Bosque", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paloma Zurita": { "ubicacion": "Área Central", "nivel": 1, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Charrán": { "ubicacion": "Costa del Este", "nivel": 7, "actividad": "Diaria", "clima": ["Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Tilopo de Wallace": { "ubicacion": "Campo de Flores (Campo del Molino)", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Lavandera Blanca": { "ubicacion": "Playa Amatista", "nivel": 4, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Malvasía Cabeciblanca": { "ubicacion": "Montaña Onsen (Orilla del Lago)", "nivel": 9, "actividad": "Diaria", "clima": ["Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Paloma de Wonga": { "ubicacion": "Bosque", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Alcaudón Común": { "ubicacion": "Suburbios", "nivel": 2, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] },
  "Papamoscas de Vientre Amarillo": { "ubicacion": "Aldea de Pescadores (Muelle)", "nivel": 5, "actividad": "Diaria", "clima": ["Soleado", "Lluvioso", "Arcoíris"], "horario": ["Noche", "Amanecer", "Día", "Atardecer"] }
};

export const ANIMALES = {
  "Carpincho (Capibara)": { "ubicacion": "Ruinas en el área del círculo", "comida_favorita": ["Frambuesa", "Tomate", "Uva"], "clima_preferido": ["Lluvioso"] },
  "Ciervo": { "ubicacion": "Entre la Torre del Ciervo y el Pinar del Roble Espíritu", "comida_favorita": ["Lechuga", "Ensalada", "Rama"], "clima_preferido": ["Soleado"] },
  "Panda": { "ubicacion": "Puzzle de Salto", "comida_favorita": ["Bambú", "Manzana", "Maíz"], "clima_preferido": ["Lluvioso"] },
  "Nutria Marina": { "ubicacion": "Puerto de la Plaza de la Aldea de Pescadores", "comida_favorita": ["Ostra", "Camarón Común", "Camarón Oriental"], "clima_preferido": ["Lluvioso"] },
  "Alpaca": { "ubicacion": "Amatista cerca del puente de madera", "comida_favorita": ["Arándano", "Piña", "Trigo"], "clima_preferido": ["Soleado"] },
  "Zorro": { "ubicacion": "Debajo del Lago del Prado", "comida_favorita": ["Carne", "Perca Europea", "Perca Americana"], "clima_preferido": ["Arcoíris"] },
  "Conejito": { "ubicacion": "Camino de la Calle del Arte hacia los suburbios", "comida_favorita": ["Hierba", "Zanahoria", "Fresa"], "clima_preferido": ["Soleado"] },
  "Hurón": { "ubicacion": "Debajo del Río Rosado cerca del puente de madera", "comida_favorita": ["Huevo", "Lubina", "Gobio"], "clima_preferido": ["Arcoíris"] }
};

export const CULTIVOS = {
  "Papa": { "tiempo_crecimiento": "60 min", "nivel_jardineria": 1, "venta_semilla": 15, "compra_semilla": 30 },
  "Tomate": { "tiempo_crecimiento": "15 min", "nivel_jardineria": 1, "venta_semilla": 5, "compra_semilla": 10 },
  "Trigo": { "tiempo_crecimiento": "4 horas", "nivel_jardineria": 2, "venta_semilla": 47, "compra_semilla": 95 },
  "Lechuga": { "tiempo_crecimiento": "8 horas", "nivel_jardineria": 3, "venta_semilla": 72, "compra_semilla": 145 },
  "Piña": { "tiempo_crecimiento": "30 min", "nivel_jardineria": 4, "venta_semilla": 7, "compra_semilla": 15 },
  "Zanahoria": { "tiempo_crecimiento": "2 horas", "nivel_jardineria": 5, "venta_semilla": 25, "compra_semilla": 50 },
  "Fresa": { "tiempo_crecimiento": "6 horas", "nivel_jardineria": 6, "venta_semilla": 62, "compra_semilla": 125 },
  "Maíz": { "tiempo_crecimiento": "12 horas", "nivel_jardineria": 6, "venta_semilla": 85, "compra_semilla": 170 },
  "Uva": { "tiempo_crecimiento": "10 horas", "nivel_jardineria": 7, "venta_semilla": 80, "compra_semilla": 160 },
  "Berenjena": { "tiempo_crecimiento": "7 horas", "nivel_jardineria": 8, "venta_semilla": 13, "compra_semilla": 35 },
  "Árbol de Té": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 11, "venta_semilla": "N/A", "compra_semilla": 25 },
  "Cacao": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 12, "venta_semilla": "N/A", "compra_semilla": 110 },
  "Aguacate": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 13, "venta_semilla": "N/A", "compra_semilla": 180 },
  "Margarita": { "tiempo_crecimiento": "18 horas", "nivel_jardineria": 3, "venta_semilla": 15, "compra_semilla": 30 },
  "Pensamiento": { "tiempo_crecimiento": "18 horas", "nivel_jardineria": 4, "venta_semilla": 15, "compra_semilla": 30 },
  "Amapola": { "tiempo_crecimiento": "1 día", "nivel_jardineria": 5, "venta_semilla": 30, "compra_semilla": 60 },
  "Anturio": { "tiempo_crecimiento": "1 día", "nivel_jardineria": 5, "venta_semilla": 30, "compra_semilla": 60 },
  "Cala": { "tiempo_crecimiento": "1 día 6 horas", "nivel_jardineria": 6, "venta_semilla": 45, "compra_semilla": 90 },
  "Ipomoea": { "tiempo_crecimiento": "1 día 6 horas", "nivel_jardineria": 6, "venta_semilla": 45, "compra_semilla": 90 },
  "Clavel": { "tiempo_crecimiento": "1 día 6 horas", "nivel_jardineria": 7, "venta_semilla": 60, "compra_semilla": 120 },
  "Tulipán": { "tiempo_crecimiento": "2 días", "nivel_jardineria": 8, "venta_semilla": 75, "compra_semilla": 150 },
  "Lirio": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 9, "venta_semilla": "N/A", "compra_semilla": 200 },
  "Rosa": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 10, "venta_semilla": "N/A", "compra_semilla": 300 },
  "Jacinto": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 11, "venta_semilla": "N/A", "compra_semilla": 300 },
  "Orquídea Mariposa": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 12, "venta_semilla": "N/A", "compra_semilla": 300 },
  "Geranio": { "tiempo_crecimiento": "N/A", "nivel_jardineria": 13, "venta_semilla": "N/A", "compra_semilla": 300 }
};

export const RECOLECTABLES = {
  "Rama": { "ubicacion": "Arbustos", "precio_venta": 5, "ganancia_energia": null },
  "Madera": { "ubicacion": "Árbol", "precio_venta": 6, "ganancia_energia": null },
  "Madera de Calidad": { "ubicacion": "Árbol", "precio_venta": 12, "ganancia_energia": null },
  "Madera Rara": { "ubicacion": "Árbol Gigante en los Suburbios", "precio_venta": 50, "ganancia_energia": null },
  "Madera de Roble Errante": { "ubicacion": "Roble Errante", "precio_venta": 150, "ganancia_energia": null },
  "Bambú": { "ubicacion": "Bambú", "precio_venta": 7, "ganancia_energia": null },
  "Piedra": { "ubicacion": "Hogar", "precio_venta": 8, "ganancia_energia": null },
  "Mineral": { "ubicacion": "Hogar", "precio_venta": 14, "ganancia_energia": null },
  "Fluorita Impecable": { "ubicacion": "Mina de Fluorita", "precio_venta": 150, "ganancia_energia": null },
  "Fragmento de Estrella": { "ubicacion": "Lluvia de Meteoritos (Mineral de Meteorito)", "precio_venta": 150, "ganancia_energia": null },
  "Manzana": { "ubicacion": "Hogar", "precio_venta": 2, "ganancia_energia": 88 },
  "Mandarina": { "ubicacion": "Hogar", "precio_venta": 2, "ganancia_energia": 88 },
  "Arándano Azul": { "ubicacion": "Hogar", "precio_venta": 1, "ganancia_energia": 65 },
  "Frambuesa": { "ubicacion": "Hogar", "precio_venta": 2, "ganancia_energia": 67 },
  "Shiitake": { "ubicacion": "Aldea de Pescadores", "precio_venta": 1, "ganancia_energia": 65 },
  "Shiitake Extraño (Negro)": { "ubicacion": "Aldea de Pescadores", "precio_venta": 16, "ganancia_energia": null },
  "Champiñón de París": { "ubicacion": "Campo de Flores", "precio_venta": 1, "ganancia_energia": 65 },
  "Boleto (Penny Bun)": { "ubicacion": "Bosque", "precio_venta": 1, "ganancia_energia": 65 },
  "Gírgola (Oyster Mushroom)": { "ubicacion": "Montaña Onsen", "precio_venta": 1, "ganancia_energia": 65 },
  "Trufa Negra": { "ubicacion": "Bosque (Isla del Bosque)", "precio_venta": 99, "ganancia_energia": 25 },
  "Matsutake": { "ubicacion": "Bosque (Pinar del Roble Espíritu)", "precio_venta": 5, "ganancia_energia": null }
};

export const HABITANTES = {
  "Doris": { 
    "rol": "Comerciante Estelar", 
    "imagen": "/npc/doris-rain.webp", 
    "descripcion": "Versión Meteorito (intercambio de fragmentos por muebles estelares) o Versión Lluvia (receta exclusiva de azúcar).", 
    "ubicacion": "Variable según el clima" 
  },
  "Albert Jr": { 
    "rol": "Comerciante", 
    "imagen": "/npc/albert-jr.webp", 
    "descripcion": "Comerciante que te permite vender tu excedente por monedas de oro.", 
    "ubicacion": "Centro del pueblo" 
  },
  "Señora Joan": { 
    "rol": "Animal Mistress", 
    "imagen": "/npc/mrs-joan.webp", 
    "descripcion": "Tienda de comida y complementos para perros/gatos.", 
    "ubicacion": "Tienda de mascotas" 
  },
  "Bailey J": { 
    "rol": "Especialista en Aves", 
    "imagen": "/npc/bailey-j.webp",  
    "descripcion": "Recompensas y evento 'Regreso al nido'.", 
    "ubicacion": "Campo de Flores" 
  },
  "Annie": { 
    "rol": "Tienda de Música",   
    "imagen": "/npc/annie.webp",   
    "descripcion": "Tienda de música, instrumentos y entretenimiento.",   
    "ubicacion": "Tienda de música" 
  },
  "Dorothee": { 
    "rol": "Diseñadora de Moda", 
    "imagen": "/npc/dorothee.webp", 
    "descripcion": "Tienda de ropa que cambia todos los días.", 
    "ubicacion": "Boutique"
  },
  "Bob": { 
    "rol": "Artesano", 
    "imagen": "/npc/bob.webp", 
    "descripcion": "El abuelo manitas de muebles construidos de forma natural.", 
    "ubicacion": "Taller de carpintería" 
  },
  "Blanc": { 
    "rol": "Jardinero Experto", 
    "imagen": "/npc/blanc.webp", 
    "descripcion": "Experto en jardinería (semillas de flores y hortalizas).", 
    "ubicacion": "Invernadero" 
  },
  "Massimo": { 
    "rol": "Chef", 
    "imagen": "/npc/massimo.webp",   
    "descripcion": "Chef (recetas y equipamiento de cocina).",  
    "ubicacion": "Restaurante" 
  },
  "Vanya": { 
    "rol": "Experta en Pesca", 
    "imagen": "/npc/vanya.webp",   
    "descripcion": "Experta en pesca (equipos y acuarios).",  
    "ubicacion": "Muelle" 
  },
  "Naniwa": { 
    "rol": "Entomóloga",  
    "imagen": "/npc/naniwa.webp",   
    "descripcion": "Vivarios, burbujas y eventos de caza de insectos.",  
    "ubicacion": "Laboratorio"
  },
  "Andrew": { 
    "rol": "Biker",   
    "imagen": "/npc/andrew.webp",   
    "descripcion": "Biker para facilitar tus viajes rápidos.",   
    "ubicacion": "Estación de transporte"
  },
  "Bill": { 
    "rol": "Capitán",  
    "imagen": "/npc/bill.webp",   
    "descripcion": "Responsable del evento 'Pesca en el mar en barco'.",   
    "ubicacion": "Puerto"
  }
};

export const RECETAS = {
  "Ensalada de Campo": { "nivel": 1, "ingredientes": "Zanahoria x2", "valores": [90, 135, 180, 360, 720], "costo": 20, "energia": [15, 18, 21, 24, 30], "rareza": "Común" },
  "Mermelada Surtida": { "nivel": 1, "ingredientes": "Cualquier Fruta x4", "valores": [160, 240, 320, 640, 1280], "costo": 120, "energia": [22, 26, 31, 35, 44], "rareza": "Común" },
  "Mermelada de Frambuesa": { "nivel": 1, "ingredientes": "Frambuesa x4", "valores": [250, 375, 500, 1000, 2000], "costo": 104, "energia": [30, 36, 42, 48, 60], "rareza": "Común" },
  "Salsa de Tomate": { "nivel": 1, "ingredientes": "Tomate x4", "valores": [180, 270, 360, 720, 1440], "costo": 120, "energia": [35, 42, 49, 56, 70], "rareza": "Común" },
  "Mermelada de Arándano": { "nivel": 1, "ingredientes": "Arándano x4", "valores": [170, 255, 340, 680, 1360], "costo": 64, "energia": [22, 26, 31, 35, 44], "rareza": "Común" },
  "Mermelada de Manzana": { "nivel": 1, "ingredientes": "Manzana x4", "valores": [270, 405, 540, 1080, 2160], "costo": 112, "energia": [35, 42, 49, 56, 70], "rareza": "Común" },
  "Mermelada de Naranja": { "nivel": 1, "ingredientes": "Mandarina x4", "valores": [270, 405, 540, 1080, 2160], "costo": 112, "energia": [35, 42, 49, 56, 70], "rareza": "Común" },
  "Mermelada de Uva": { "nivel": 1, "ingredientes": "Uva x4", "valores": [2020, 3030, 4040, 8080, 16160], "costo": 640, "energia": [40, 48, 56, 64, 80], "rareza": "Común" },
  "Mermelada de Fresa": { "nivel": 1, "ingredientes": "Fresa x4", "valores": [1580, 2370, 3160, 6320, 12640], "costo": 1500, "energia": [40, 48, 56, 56, 80], "rareza": "Común" },
  "Mermelada de Piña": { "nivel": 1, "ingredientes": "Piña x4", "valores": [280, 420, 560, 1120, 2240], "costo": 60, "energia": [40, 48, 56, 64, 80], "rareza": "Común" },
  "Pescado con Patatas": { "nivel": 1, "ingredientes": "Cualquier Pescado x2, Patata x2", "valores": [310, 465, 620, 1240, 2480], "costo": 280, "energia": [40, 48, 56, 56, 80], "rareza": "Común" },
  "Comida Extraña": { "nivel": 1, "ingredientes": "Fallar ajuste de calor en estufa", "valores": [30, 45, 60, 120, 240], "costo": null, "energia": [10, 12, 14, 16, 20], "rareza": "Común" },
  "Bebida Extraña": { "nivel": 1, "ingredientes": "Fallar cualquier receta de bebida", "valores": [30, 45, 60, 120, 240], "costo": null, "energia": [10, 12, 14, 16, 20], "rareza": "Común" },
  "Champiñones Asados": { "nivel": 1, "ingredientes": "Cualquier Champiñón x4", "valores": [180, 270, 360, 720, 1440], "costo": 64, "energia": [15, 18, 21, 24, 30], "rareza": "Común" },
  "Salsa de Chocolate": { "nivel": 1, "ingredientes": "Cacao x4", "valores": [200, 300, 400, 800, 1600], "costo": 100, "energia": [25, 30, 35, 40, 50], "rareza": "Común" },
  "Tarta de Queso": { "nivel": 2, "ingredientes": "Queso x1, Trigo x1, Leche x1", "valores": [480, 720, 960, 1920, 3840], "costo": 435, "energia": [50, 60, 70, 80, 100], "rareza": "Común" },
  "Rollo de Nubes Original": { "nivel": 1, "ingredientes": "Huevo x1, Leche x1, Azúcar Blanco x2", "valores": [550, 825, 1100, 2200, 4400], "costo": 450, "energia": [35, 42, 49, 56, 70], "rareza": "Común" },
  "Rollo de Nubes Rojo": { "nivel": 1, "ingredientes": "Huevo x1, Leche x1, Azúcar Rojo x2", "valores": [670, 1005, 1340, 2680, 5360], "costo": 450, "energia": [48, 58, 67, 77, 96], "rareza": "Común" },
  "Rollo de Nubes Naranja": { "nivel": 1, "ingredientes": "Huevo x1, Leche x1, Azúcar Naranja x2", "valores": [670, 1005, 1340, 2680, 5360], "costo": 550, "energia": [48, 58, 67, 77, 96], "rareza": "Común" },
  "Rollo de Nubes Amarillo": { "nivel": 1, "ingredientes": "Huevo x1, Leche x1, Azúcar Amarillo x2", "valores": [670, 1005, 1340, 2680, 5360], "costo": 450, "energia": [48, 58, 67, 77, 96], "rareza": "Común" },
  "Rollo de Nubes Verde": { "nivel": 1, "ingredientes": "Huevo x1, Leche x1, Azúcar Verde x2", "valores": [670, 1005, 1340, 2680, 5360], "costo": 550, "energia": [48, 58, 67, 77, 96], "rareza": "Común" },
  "Rollo de Nubes Azul": { "nivel": 1, "ingredientes": "Huevo x1, Leche x1, Azúcar Azul x2", "valores": [570, 855, 1140, 2280, 4560], "costo": 450, "energia": [48, 58, 67, 77, 96], "rareza": "Común" },
  "Rollo de Nubes Indigo": { "nivel": 1, "ingredientes": "Huevo x1, Leche x1, Azúcar Indigo x2", "valores": [570, 855, 1140, 2280, 4560], "costo": 450, "energia": [48, 58, 67, 77, 96], "rareza": "Común" },
  "Rollo de Nubes Violeta": { "nivel": 1, "ingredientes": "Huevo x1, Leche x1, Azúcar Violeta x2", "valores": [570, 855, 1140, 2280, 4560], "costo": 450, "energia": [48, 58, 67, 77, 96], "rareza": "Común" },
  "Tarta de Champiñones": { "nivel": 1, "ingredientes": "Cualquier Champiñón x2, Trigo x1, Huevo x1", "valores": [500, 750, 1000, 2000, 4000], "costo": 195, "energia": [35, 42, 49, 56, 70], "rareza": "Común" },
  "Tarta de Trufa Negra": { "nivel": 3, "ingredientes": "Trufa x1, Trigo x2, Leche x1", "valores": [830, 1245, 1660, 3320, 6640], "costo": 583, "energia": [80, 96, 112, 128, 160], "rareza": "Raro" },
  "Café": { "nivel": 1, "ingredientes": "Granos de Café x4", "valores": [290, 435, 580, 1160, 2320], "costo": 200, "energia": [40, 48, 56, 56, 80], "rareza": "Común" },
  "Café con Leche": { "nivel": 1, "ingredientes": "Granos de Café x2, Leche x2", "valores": [300, 450, 600, 1200, 2400], "costo": 200, "energia": [40, 48, 56, 56, 80], "rareza": "Común" },
  "Bagel de Pescado Ahumado": { "nivel": 2, "ingredientes": "Pescado x1, Queso x1, Zanahoria x1, Trigo x1", "valores": [520, 780, 1040, 2080, 4160], "costo": 245, "energia": [50, 60, 70, 80, 100], "rareza": "Raro" },
  "Risotto de Mariscos": { "nivel": 3, "ingredientes": "Mariscos x2, Trigo x1, Tomate x1", "valores": [490, 735, 980, 1960, 3920], "costo": 105, "energia": [50, 60, 70, 80, 100], "rareza": "Raro" },
  "Guiso Rústico (Ratatouille)": { "nivel": 3, "ingredientes": "Tomate x1, Patata x1, Lechuga x1", "valores": [640, 960, 1280, 2560, 5120], "costo": 185, "energia": [60, 72, 84, 96, 120], "rareza": "Raro" },
  "Pasta con Crema de Trufa": { "nivel": 3, "ingredientes": "Trufa x1, Trigo x2, Leche x1", "valores": [900, 1350, 1800, 3600, 7200], "costo": 719, "energia": [90, 108, 126, 144, 180], "rareza": "Épico" },
  "Pasta Boloñesa": { "nivel": 4, "ingredientes": "Carne x1, Trigo x1, Tomate x1, Queso x1", "valores": [670, 1005, 1340, 2680, 5360], "costo": 405, "energia": [80, 96, 112, 128, 160], "rareza": "Raro" },
  "Pizza de Mariscos": { "nivel": 4, "ingredientes": "Queso x1, Mermelada/Salsa x1, Trigo x1, Pescado x1", "valores": [780, 1170, 1560, 3120, 6240], "costo": 240, "energia": [70, 84, 98, 112, 140], "rareza": "Raro" },
  "Set de Picnic": { "nivel": 7, "ingredientes": "Pizza de Mariscos, Tarta de Manzana, Pescado con Patatas, Cualquier Bebida", "valores": [2260, 3390, 4520, 9040, 18080], "costo": null, "energia": [140, 160, 196, 224, 280], "rareza": "Legendario" },
  "Sashimi de Cangrejo": { "nivel": 8, "ingredientes": "Mariscos x3, Lechuga x1", "valores": [850, 1275, 1700, 3400, 6800], "costo": 145, "energia": [30, 36, 42, 48, 60], "rareza": "Raro" },
  "Cena a la Luz de las Velas": { "nivel": 9, "ingredientes": "Ensalada de Campo, Bagel Ahumado, Risotto de Mariscos, Tiramisú", "valores": [1760, 2640, 3520, 7040, 14080], "costo": null, "energia": [75, 90, 105, 120, 150], "rareza": "Legendario" },
  "Té de la Tarde": { "nivel": 7, "ingredientes": "Tiramisú x1, Cualquier Fruta/Verdura x1", "valores": [710, 1065, 1420, 2840, 5680], "costo": 460, "energia": [20, 30, 35, 40, 50], "rareza": "Épico" },
  "Tarta de Manzana": { "nivel": 5, "ingredientes": "Manzana x1, Trigo x1, Huevo x1, Mantequilla x1", "valores": [730, 1095, 1460, 2920, 5840], "costo": 345, "energia": [70, 84, 98, 112, 140], "rareza": "Raro" },
  "Pastel de Zanahoria": { "nivel": 5, "ingredientes": "Zanahoria x2, Trigo x1, Leche x1", "valores": [840, 1260, 1680, 3360, 6720], "costo": 695, "energia": [55, 66, 77, 88, 110], "rareza": "Raro" },
  "Sopa de Maíz": { "nivel": 5, "ingredientes": "Leche x1, Mantequilla x1, Maíz x2", "valores": [1340, 2010, 2680, 5360, 10720], "costo": 540, "energia": [80, 96, 112, 128, 160], "rareza": "Raro" },
  "Tiramisú": { "nivel": 6, "ingredientes": "Granos de Café x1, Huevo x1, Leche x1, Queso x1", "valores": [530, 795, 1060, 2120, 4240], "costo": 300, "energia": [65, 78, 91, 104, 130], "rareza": "Raro" },
  "Plato de Mariscos Deluxe": { "nivel": 6, "ingredientes": "Mariscos x2, Pescado x2", "valores": [410, 615, 820, 1640, 3280], "costo": null, "energia": [65, 78, 91, 104, 130], "rareza": "Raro" },
  "Hamburguesa de Carne": { "nivel": 8, "ingredientes": "Trigo x1, Lechuga x1, Carne x1, Mermelada x1", "valores": [1350, 2025, 2700, 5400, 10800], "costo": 480, "energia": [75, 90, 105, 120, 150], "rareza": "Épico" },
  "Berenjena Asada con Carne": { "nivel": 9, "ingredientes": "Berenjena x1, Carne x1, Aceite x1, Mermelada x1", "valores": [1230, 1845, 2460, 4920, 9840], "costo": 475, "energia": [75, 90, 105, 120, 150], "rareza": "Épico" },
  "Té Negro Suave": { "nivel": 11, "ingredientes": "Desconocido", "valores": [3000, 4500, 6000, 12000, 24000], "costo": null, "energia": [100, 120, 140, 160, 200], "rareza": "Legendario" },
  "Batido": { "nivel": 11, "ingredientes": "Desconocido", "valores": [3200, 4800, 6400, 12800, 25600], "costo": null, "energia": [110, 132, 154, 176, 220], "rareza": "Legendario" },
  "Té Verde Refrescante": { "nivel": 12, "ingredientes": "Desconocido", "valores": [3500, 5250, 7000, 14000, 28000], "costo": null, "energia": [120, 144, 168, 192, 240], "rareza": "Legendario" },
  "Té de la Tarde Exquisito": { "nivel": 12, "ingredientes": "Desconocido", "valores": [4000, 6000, 8000, 16000, 32000], "costo": 6400, "energia": [130, 156, 182, 208, 260], "rareza": "Legendario" },
  "Copa de Langostinos y Aguacate": { "nivel": 13, "ingredientes": "Desconocido", "valores": [0, 0, 0, 0, 0], "costo": null, "energia": [0, 0, 0, 0, 0], "rareza": "Legendario" },
"Cangrejo Real al Vapor": { "nivel": 10, "ingredientes": "Desconocido", "valores": [0, 0, 0, 0, 0], "costo": null, "energia": [0, 0, 0, 0, 0], "rareza": "Legendario" },
"Cangrejo Relleno de Queso y Camarones": { "nivel": 13, "ingredientes": "Desconocido", "valores": [0, 0, 0, 0, 0], "costo": null, "energia": [0, 0, 0, 0, 0], "rareza": "Legendario" },

};

export const LOGROS = {
  "Nunca con las manos vacías": { "requisito": "Nivel 10 en el hobby de Pesca", "titulo": "Pescador Místico", "nota": "Skilled Angler", "imagen": "/logros/never-empty-handed.webp" },
  "Pescador Místico": { "requisito": "Activa la fase oculta del Evento de Pesca 10 veces en total", "titulo": "Pescador", "nota": "Fisher", "imagen": "/logros/mystic-fisher.webp" },
  "Bendición del Cardumen": { "requisito": "Activa 100 cardúmenes en total durante eventos de pesca", "titulo": "Bendición", "nota": "Blessing", "imagen": "/logros/shoals-blessing.webp" },
  "Marinero Fuerte": { "requisito": "Atrapa peces de más de 100kg por 2 veces consecutivas", "titulo": "Sedal de Pesca", "nota": "Fishing Line", "imagen": "/logros/strong-sailor.webp" },
  "Fortuna de Peces Gemelos": { "requisito": "Atrapa 2 peces de 5 estrellas en menos de 1 minuto", "titulo": "Águila Pescadora", "nota": "Osprey", "imagen": "/logros/twin-fish-fortune.webp" },
  "Máquina de Pesca": { "requisito": "Atrapa un total de 50 peces de más de 100kg cada uno", "titulo": "Cesta de Peces", "nota": "Fish Basket", "imagen": "/logros/fishing-machine.webp" },
  "Frenesí de Tiburones": { "requisito": "Atrapa 3 tiburones de sombras doradas en un solo evento de pesca marina", "titulo": "Jaula de Tiburones", "nota": "Shark Cage", "imagen": "/logros/shark-frenzy.webp" },
  "Invocador de Cardúmenes": { "requisito": "Activa 3 cardúmenes en un solo evento de pesca", "titulo": "Invocador de Cardúmenes", "nota": "Shoal Caller", "imagen": "/logros/shoal-caller.webp" },
  "Pescador de Luz Estelar": { "requisito": "Atrapa 4 peces de 5 estrellas en un solo evento de pesca", "titulo": "Maníaco de la Pesca", "nota": "Fishing Maniac", "imagen": "/logros/starlight-fisher.webp" },
  "Leyenda de la Cocina del Pueblo": { "requisito": "Nivel 10 en el hobby de Cocina", "titulo": "Chef", "nota": "Chef", "imagen": "/logros/town-cooking-legend.webp" },
  "Rápido y Perfecto": { "requisito": "Cocina 2 platos de 5 estrellas en menos de 60 segundos", "titulo": "Reloj de Cocina", "nota": "Kitchen Clock", "imagen": "/logros/fast-and-lawless.webp" },
  "Toque Verde": { "requisito": "Nivel 10 en el hobby de Jardinería", "titulo": "Horticultor", "nota": "Horticulturist", "imagen": "/logros/green-touch.webp" },
  "Cosecha Abundante": { "requisito": "Cosecha cultivos de 5 estrellas mientras la Cosecha de Bonificación está activa", "titulo": "Cosecha", "nota": "Harvest", "imagen": "/logros/plentiful-harvest.webp" },
  "Suerte del Arcoíris": { "requisito": "Activa 2 bendiciones híbridas de arcoíris en un solo riego de área múltiple", "titulo": "Suerte del Arcoíris", "nota": "Rainbow Luck", "imagen": "/logros/rainbow-luck.webp" },
  "Sirviente Gatuno Ace": { "requisito": "Nivel 10 en el hobby de Cuidado de Gatos", "titulo": "Amante de los Gatos", "nota": "Cat Lover", "imagen": "/logros/ace-cat-servant.webp" },
  "Cantina Miau-Miau": { "requisito": "Alimenta a 5 gatos con su comida favorita", "titulo": "Comida para Gatos", "nota": "Cat Food", "imagen": "/logros/meow-meow-canteen.webp" },
  "Entrenador de Perros Ace": { "requisito": "Nivel 10 en el hobby de Cuidado de Perros", "titulo": "Amigo de los Perros", "nota": "Dog Pal", "imagen": "/logros/ace-dog-trainer.webp" },
  "Cantina Perruna": { "requisito": "Alimenta a 3 perros con su comida favorita", "titulo": "Comida para Perros", "nota": "Dog Food", "imagen": "/logros/doggie-canteen.webp" },
  "Comandante de Insectos": { "requisito": "Nivel 10 en el hobby de Captura de Insectos", "titulo": "Maestro de Insectos", "nota": "Insect Master", "imagen": "/logros/insect-commander.webp" },
  "Rastreador Místico": { "requisito": "Activa la fase oculta del evento de captura de insectos 10 veces", "titulo": "Exploración", "nota": "Exploration", "imagen": "/logros/mystic-tracker.webp" },
  "Recolector de Insectos": { "requisito": "Atrapa 3 insectos con una sola burbuja de captura", "titulo": "Triple Captura", "nota": "Triple Catch", "imagen": "/logros/insect-harvester.webp" },
  "Susurrador de Aves": { "requisito": "Nivel 10 en el hobby de Avistamiento de Aves", "titulo": "Susurrador de Aves", "nota": "Bird Whisperer", "imagen": "/logros/bird-whisperer.webp" },
  "Caminante de Nubes": { "requisito": "Activa la fase oculta del evento de aves 10 veces", "titulo": "Cielo", "nota": "Sky", "imagen": "/logros/cloud-walker.webp" },
  "Artista de Esculturas de Arena": { "requisito": "Nivel 5 en el hobby de Esculturas de Arena", "titulo": "Escultor de Arena", "nota": "Sand Sculptor", "imagen": "/logros/sand-sculpture-artist.webp" },
  "Patrocinador de Cohetes": { "requisito": "Gana un total de 500,000 de Oro vendiendo a Albert Jr.", "titulo": "Cohete", "nota": "Rocket", "imagen": "/logros/rocket-sponsor.webp" },
  "Miembro D.G.": { "requisito": "Alcanza el nivel 30 de Miembro D.G.", "titulo": "Miembro D.G.", "nota": "D.G. Member", "imagen": null },
  "Vecino Animal": { "requisito": "Alcanza el nivel 10 de vínculo con 8 grupos de animales", "titulo": "Nuevo Vecino", "nota": "New Neighbour", "imagen": "/logros/animal-neighbors.webp" },
  "Guardián de Animales": { "requisito": "Descubre la comida favorita de 8 grupos de animales", "titulo": "Delicioso", "nota": "Delicious", "imagen": "/logros/animal-sitter.webp" },
  "Experto en Reparaciones": { "requisito": "Comparte kits de reparación con 100 miembros D.G. en total", "titulo": "Reparaciones", "nota": "Repairs", "imagen": "/logros/repair-expert.webp" },
  "Estrella del Pop": { "requisito": "Recibe un total de 100 Likes en tu casa", "titulo": "Estrella Naciente", "nota": "Rising Star", "imagen": "/logros/star.webp" },
  "Compañero de Onsen": { "requisito": "Toma un baño termal con amigos", "titulo": "Onsen", "nota": "Onsen", "imagen": "/logros/friends-of-the-hot-springs.webp" },
  "Bajo la Lluvia de Meteoritos": { "requisito": "Pide un deseo bajo un meteorito con amigos", "titulo": "Géminis", "nota": "Gemini", "imagen": null }
};

export const CATEGORIES = [
  { id: 'peces', name: 'Peces', icon: 'Fish', description: 'Guía completa de pesca', count: Object.keys(PECES).length },
  { id: 'insectos', name: 'Insectos', icon: 'Bug', description: 'Captura de insectos', count: Object.keys(INSECTOS).length },
  { id: 'aves', name: 'Aves', icon: 'Bird', description: 'Avistamiento de aves', count: Object.keys(AVES).length },
  { id: 'animales', name: 'Animales', icon: 'Paw', description: 'Animales salvajes', count: Object.keys(ANIMALES).length },
  { id: 'cultivos', name: 'Cultivos', icon: 'Leaf', description: 'Jardinería y flores', count: Object.keys(CULTIVOS).length },
  { id: 'recolectables', name: 'Recolectables', icon: 'TreeDeciduous', description: 'Recursos del mundo', count: Object.keys(RECOLECTABLES).length },
  { id: 'habitantes', name: 'Habitantes', icon: 'Users', description: 'NPCs del pueblo', count: Object.keys(HABITANTES).length },
  { id: 'recetas', name: 'Recetas', icon: 'ChefHat', description: 'Cocina y comida', count: Object.keys(RECETAS).length },
  { id: 'logros', name: 'Logros', icon: 'Trophy', description: 'Títulos y logros', count: Object.keys(LOGROS).length },
];

export type CategoryId = 'peces' | 'insectos' | 'aves' | 'animales' | 'cultivos' | 'recolectables' | 'habitantes' | 'recetas' | 'logros';

export function getCategoryData(categoryId: CategoryId) {
  switch (categoryId) {
    case 'peces': return PECES;
    case 'insectos': return INSECTOS;
    case 'aves': return AVES;
    case 'animales': return ANIMALES;
    case 'cultivos': return CULTIVOS;
    case 'recolectables': return RECOLECTABLES;
    case 'habitantes': return HABITANTES;
    case 'recetas': return RECETAS;
    case 'logros': return LOGROS;
    default: return {};
  }
}
